### ISSUE TITLE
binary file

### ISSUE THREAD

**Issue by iddq** [rdiez/JtagDue#1]
Hello, can you please upload the linked binary file into the repo?

**Comment by rdiez** [comment]
There is only one binary at the moment, and it is in a separate repository, as stated in the readme file. It is here:
https://github.com/rdiez/JtagDueBinaries/tree/master/LatestRelease

**Comment by iddq** [comment]
can you please update the binary file?

**Comment by rdiez** [comment]
Are you having any issues with that binary? It should work fine.

**Comment by iddq** [comment]
no, I just see your project is recently updated and that binary is 6 years old.

**Comment by rdiez** [comment]
I haven't done any changes to the project (JTAG) functionality. Well, maybe with the new compiler version it could run a little faster, but a binary upgrade is not really worth it.
